### PR TITLE
Unsolicited: Minor improvements.

### PR DESCRIPTION
**Pull request by Alaricus**
I was bored on a plane, so I messed with the code a bit:

1. Went through the codebase and replaced all magic numbers related to tile sizing (40px) with reference to the SPRITE_SIZE from constants.js

2. Updated CSS values for height and width to include units, so `width: 40px;` instead of `width: 40;`

3. Switched around the tiles for entrance an exit. My reasoning is that since we are dealing with a dungeon, not a tower, each subsequent level should be lower than the previous one. That necessitates going down the stairs to progress to the next level.

Also, @ASteinheiser, let's talk about formatting. I'm not sure I'm a fan of using spaces to organize object literals and imports. I used to do the same thing, and it can look pretty, but in the long run it actually creates discrepancies and unnecessary work. Linting best practices recommend against using this sort of "ASCII art" to beautify code. Not saying we should sit down and redo it all, but perhaps as we touch different files we could avoid using this style. What do you think?

### CODE REVIEW

**Comment by ASteinheiser** [comment]
@Alaricus To be honest, I really like spacing the imports like that, because it makes it easier for me to read. I also like to have modules at the top then local imports. If you can show me an article or convince me otherwise, I could change my mind.

That being said, good catch on those tile size constants!

I can understand what you mean with the stairs. However, if you want to change that, I would like to also change the places that reference "up" or "down" and change their meaning (such as `data/maps` and `player/walk-stairs`). Honestly, I think it could be fine just going up. The story really isn't set in stone. For all we know, it could be a tower!

**Comment by ASteinheiser** [comment]
@Alaricus I am willing to accept this PR if you add another commit for changing the references to "up" and "down".  The files that would need a little love are:

`/data/maps` (each map should switch `up` and `down` values on `stairs` object)

`/features/map/random-map-gen/generate-objects.js` (the comments are now backwards)

`/features/player/actions/walk-stairs.js` (the values for up and down are backwards, then the checks for directions need to be swapped as well. should be 4 lines to change)

`/features/dialog-manager/reducer.js` (showing the message should only happen on "down" in `SET_STORY_MAP` reducer)

I believe that should be the only changes needed. If I missed anything, definitely let me know.

And one minor thing; in `backpack-items` you made the constants at the top for height to be lowercased. I prefer to keep all constants uppercase. I like that you renamed those variables to be more descriptive, but could you just capitalize them?

**Comment by Alaricus** [comment]
@ASteinheiser, sorry, was busy. I'll take a look and push out the updates.

**Comment by Alaricus** [comment]
I updated the up and down and tested them in both story and endless modes. That said, the users with existing local storage objects will experience a crash, because the objects in local storage are still old. One way to solve this (I've done it in another game of mine) is to check the build's version against the version in local storage and delete local storage if there's a mismatch. Of course, that causes the user to lose progress, so it will be up to you to decide how you want to go about it.

As to the `backpack-items`, I actually did that on purpose, because those variables are no longer constants. At this point they are calculated values based on actual constants that we import. If the actual constants will change, then the values will change as well.

**Comment by ASteinheiser** [comment]
@Alaricus So I really don't want to wipe everyone's game when we release small updates. We could introduce a system like you're talking about, but only wipe on minor versions, not patch.

I added a `componentDidCatch()` to the index for the entire game. I figure this could catch your crash as well, but I guess it didn't. I make sure to clear the cache and refresh if we hit that `componentDidCatch()`. This fixed some crashes when I drastically changed the redux store and people had old versions.

I will try out your PR tonight and see what I can do about the crashing.

**Comment by ASteinheiser** [comment]
Hmm... Yeah, I can see that crash when you have the old map data.

My `componentDidCatch` only seems to catch when an old redux store is incompatible with a new version. This is good, since it wipes the data and refreshes (we don't want that to be infinite).

I think to release this change, we need to have something in the app state that keeps the latest version and checks with the current version. Then wipe the data if we bump the minor version (1.X.0).

**Pull request closed without merging**
