### PR TITLE
feature: Add simple wait command for web

### PR DESCRIPTION
**Pull request by Alphanumber**
Quick and dirty wait feature only for keyboard. Might be overpowered in the current iteration but being able to wait would be nice.

Will try to think of good touch implementation.

### CODE REVIEW

**Comment by ASteinheiser** [comment]
Thank you for submitting the first PR!

So as for this feature, the easiest way to implement it for both touch and keyboard, would be to remove the code I have around the player attack, the makes it so a turn is not taken when the player swings at nothing. If you just took a turn when the player swings at nothing, you will have a "wait" command for both input controls.

That being said, I think introducing a wait command is overpowered because right now, the game relies on chance as to whether the player or monster gets first attack. (The monsters have a random chance to not move when out of sight, otherwise moves randomly). Because of this reason, I will need to decline this pull request.

**Comment by Alphanumber** [comment]
What's the specific design intent in terms of feel and progression? I'd love to contribute to the project so I want to align with your vision on what the game will be long term. I made the pull request before I read some of your reddit comments so I wasn't aware of what you were thinking of in terms of design.

Being able to pass a turn seems like an obvious feature to help traverse the dungeon since the player's success depends largely on being able to mitigate/avoid damage once the DPS race begins. Being forced to cede initiative even when the player can see the enemy coming feels similar to not getting equipment drops. Additionally, I think darting in and out of the fog seems to allow re-rolling for more favorable initiative outcomes, which possibly could encourage odd play patterns. I found myself walking back and forth if I saw the path to an enemy would not give me first strike.

When I finally killed the Lich, the run precluded avoiding damage and as such I highly valued potions to keep health high. I didn't have a set of boots until I reached the end since I was buying a potion each visit. While the health and damage management game can be rewarding broadly speaking, I think adding some tactical nuance would be welcome. Something as simple as broadcasting attack effect and range for enemy attacks that conclude the following turn could add a lot of decision making.

**Comment by ASteinheiser** [comment]
I definitely need to outline my intentions for game feel and all that. I added an issue to include a Roadmap, and I feel like that would be a good place to state my intentions.

That's a good point about poking in and out of fog. It does make for some weird gameplay behavior. I am open to changing this, however I cannot see a clear path of how to do so. If you have a solid idea, please make a github issue, as it will be easier to track and discuss in detail.

I like the idea of adding more tactical nuance, however, could you clarify what you mean by: "Something as simple as broadcasting attack effect and range for enemy attacks that conclude the following turn could add a lot of decision making." ?

Thanks again for keeping up on Reddit and submitting a PR!

**Comment by Alphanumber** [comment]
I'll open an issue for discussing the fog of war in relation to combat initiative but I don't have a particular direction either for the design.

For the other point, to be more concise, I think enemies should have attacks that take more than one turn to resolve and/or they'll also telegraph their attacks. A recent game as example is _Into The Breach_. The enemy attacks initiate and colors the tactical grid with their attack pattern. Some subsequent turn, the attack actually comes out. If the attack patterns are sufficient interesting, the player being able to see the attack opens up some fun designs.

**Comment by ASteinheiser** [comment]
Ah, I see what you are saying now. I will create an issue for that. I think it's a good suggestion.

**Pull request closed without merging**
