### PR TITLE
Fix/surrounding tiles tests

### PR DESCRIPTION
**Pull request by ASteinheiser**
@Santroi Check out this branch. I believe it should answer those questions that you had. Does this all look good to you?

### CODE REVIEW

**Comment by Saintroi** [comment]
@ASteinheiser This definitely resolves the issues, and I understand what you were talking about now. 

The only thing I'm questioning is that MAP_DIMENSIONS seems to be (y, x) but now everything else is (x, y) and so you end up getting X values from MAP_DIMENSIONS[1] and Y values from MAP_DIMENSIONS[0] 

If that's the only thing set up like that why not just swap those hard-coded numbers in MAP_DIMENSIONS and make it (x, y) like everything else? Just for clarity's sake.

Proposed change: 
/src/config/constants.js
Line 13
from ```export const MAP_DIMENSIONS = [TILE_HEIGHT, TILE_WIDTH];```
to ```export const MAP_DIMENSIONS = [TILE_WIDTH, TILE_HEIGHT];```

Then adjust indices in appropriate places.

**Comment by ASteinheiser** [comment]
@Saintroi I can understand that. I definitely overlooked that during the refactor. There's a lot of changes associated with this however (30+). I will try it out and test to make sure everything is alright. I would appreciate some QA once I merge it into staging :).

**Comment by ASteinheiser** [comment]
Let's test on staging.react-rpg.com and if we can't find any bugs, I'll merge it into master!

This closes #67.

@allcontributors[bot] add @Saintroi for tests and ideas

**Comment by Saintroi** [comment]
@ASteinheiser Awesome man. From my limited testing, seems to be good so far. I'll try and dive in deeper in a bit. Glad we could get this small (but annoying) issue resolved lol, hopefully now I can actually focus and see where I can contribute!

**Pull request merged**
