### PR TITLE
Deactivate viewport user scaling

### LINKED ISSUE #19: Disable double-tap to zoom on iOS Safari
I tried the advice here, and still no luck!
https://stackoverflow.com/questions/51041393/how-to-disable-viewport-zooming-in-ios-11-3-safari

### PR DESCRIPTION
**Pull request by ajrussellaudio**
Removes user scaling from the HTML meta tag.

This fixes #19

### CODE REVIEW

**Comment by ASteinheiser** [comment]
Were you able to test on Safari on an iOS device?

**Comment by ajrussellaudio** [comment]
I only have my own iPhone SE to test on and there are other issues with the layout on that model as you're tracking in #29, but yes, I've tested it in Safari and Chrome on iOS 12.2 and both double tapping and pinch to zoom are disabled. The viewport can't be zoomed at all.

**Comment by ASteinheiser** [comment]
Gotcha, sound great! Just because I've had so much trouble with this bug, I want to test this on a device as well. I seem to be having issues when testing on a simulator, so I will try on an actual device soon.

**Comment by ASteinheiser** [comment]
@ajrussellaudio Oh and I just remembered... when I asked if you tested it, were you able to test it in the native app as well? I am not sure, but the WebView might screw with some things. I just remember this bug being really annoying. You can spin up the native app from [this repo](https://github.com/ASteinheiser/ReactRPGNative), then just change the `GAME_URL` in `src/App.js`.

**Comment by ASteinheiser** [comment]
Alright @ajrussellaudio, I will merge this code. Can you actually create another PR and merge into staging instead of master? Thanks.

**Pull request closed without merging**
